[package]
name = "musicshell"
version = "0.2.1"
edition = "2024"

[dependencies]
anyhow = "1.0.97"
bincode = "1.3.3"
crossterm = "0.28.1"
ratatui = "0.29.0"
rodio = "0.20.1"
serde = { version = "1.0.219", features = ["derive"] }
toml = "0.8.20"
